In [1]:
import pandas as pd
import psycopg2

In [ ]:
# Connect to PostgreSQL

conn = psycopg2.connect(
    host="localhost",
    database="bank_reviews",
    user="postgres",
    password="Talieynaso1996&4"
)

In [3]:
# Define a Helper Function to Run SQL and Return DataFrame

def run_query(sql):
    return pd.read_sql(sql, conn)

In [4]:
sql = "SELECT * FROM reviews;"

run_query(sql)

C:\Users\ZAK-TECH\AppData\Local\Temp\ipykernel_1068\1241105332.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(sql, conn)

,review_id,review_text,rating,bank_code,bank_name,source
0,3463230e-f9f7-4be3-a632-fdd8d017ce84,🙏👍,5,BOA,BOA,Google Play
1,a6cbfa34-f2b1-4a16-96b6-c94f58cea76f,Very Good,5,BOA,BOA,Google Play
2,fc67d12c-92e2-45aa-a9e0-011f58a583bc,goof,5,BOA,BOA,Google Play
3,11306fb9-5571-4950-8d32-604c5402242f,good!,5,BOA,BOA,Google Play
4,809c46d2-730e-446a-9061-2a45e978ad9d,good jop,5,BOA,BOA,Google Play
...,...,...,...,...,...,...
1195,b3c8405c-96a7-4b5e-884c-76c97c530c34,good,5,DASHEN,DASHEN,Google Play
1196,e1c1214a-8bc1-45db-bc49-3d51dddc6b88,Amazing app super easy to use and best design....,5,DASHEN,DASHEN,Google Play
1197,8d1d472b-2bae-4749-b089-5632108ade02,its the best ever,5,DASHEN,DASHEN,Google Play
1198,749851ed-72d7-4f1c-8e5e-27dd822b5008,nice,5,DASHEN,DASHEN,Google Play
1199,f2852962-b983-44af-b296-241a3373477f,excellent game changer App,5,DASHEN,DASHEN,Google Play

In [5]:
sql = "SELECT * FROM banks;"

run_query(sql)

C:\Users\ZAK-TECH\AppData\Local\Temp\ipykernel_1068\1241105332.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(sql, conn)

,bank_id,app_id,title,score,ratings,reviews,installs,bank_code,bank_name
0,4,com.combanketh.mobilebanking,Commercial Bank of Ethiopia,4.319238,38870,8338,"5,000,000+",CBE,Commercial Bank of Ethiopia
1,5,com.boa.boaMobileBanking,BoA Mobile,4.172685,6366,1219,"1,000,000+",BOA,BOA
2,6,com.dashen.dashensuperapp,Dashen Bank,4.168704,3915,773,"1,000,000+",DASHEN,DASHEN

In [13]:
# Count reviews per bank

sql = """
SELECT 
    b.bank_name,
    COUNT(*) AS total_reviews,
    ROUND(AVG(r.rating)::numeric, 2) AS avg_rating
FROM reviews r
JOIN banks b ON b.bank_code = r.bank_code
GROUP BY b.bank_name
ORDER BY avg_rating DESC;
"""

run_query(sql)

C:\Users\ZAK-TECH\AppData\Local\Temp\ipykernel_1068\1241105332.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(sql, conn)

                     bank_name  total_reviews  avg_rating
0  Commercial Bank of Ethiopia            400        4.13
1                       DASHEN            400        3.96
2                          BOA            400        3.38

In [11]:
# Average rating per review 

sql = """
SELECT 
    b.bank_name,
    COUNT(*) AS total_reviews,
    ROUND(AVG(r.rating)::numeric, 2) AS avg_rating
FROM reviews r
JOIN banks b ON b.bank_code = r.bank_code
GROUP BY b.bank_name
ORDER BY total_reviews DESC;
"""

run_query(sql)

C:\Users\ZAK-TECH\AppData\Local\Temp\ipykernel_1068\1241105332.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(sql, conn)

                     bank_name  total_reviews  avg_rating
0                          BOA            400        3.38
1                       DASHEN            400        3.96
2  Commercial Bank of Ethiopia            400        4.13